### ISSUE TITLE
Reclaimed by Dan Risacher?

### ISSUE THREAD

**Issue by petermarkley** [klada/sunwait#5]
Looks like Dan Risacher has reappeared and created his own Github repo for this: https://github.com/risacher/sunwait

Maybe we should try to compare the best changes across both repos and decide on an authoritative maintainer again?

**Comment by klada** [comment]
This is good news. I will archive this repository then as it was only intended as a mirror and I did not do any actual development besides the Debian packaging.

I have also added a link in the README.
